const htmlMinifier = require('html-minifier');
const cheerio = require('cheerio');
const chalk = require('chalk');
const prettyBytes = require('pretty-bytes');

module.exports = function minify(originalHTML, logs = false) {
    function log(...args) {
        if (logs) {
            console.log(...args);
        }
    }

    let html = originalHTML;

    log(chalk.bold('Size before:'), chalk.blue(prettyBytes(html.length)));

    const $ = cheerio.load(html);
    $('script').remove();

    html = $.html();

    log(
        chalk.bold('Size after cheerio:'),
        chalk.blue(prettyBytes(html.length))
    );
    const minifiedOptions = {
        caseSensitive: false,
        collapseBooleanAttributes: true,
        collapseInlineTagWhitespace: true,
        collapseWhitespace: true,
        decodeEntities: true,
        html5: true,
        ignoreCustomComments: [],
        includeAutoGeneratedTags: false,
        keepClosingSlash: false,
        minifyCSS: true,
        minifyJS: true,
        preserveLineBreaks: false,
        preventAttributesEscaping: false,
        processConditionalComments: true,
        processScripts: [],
        quoteCharacter: '"',
        removeAttributeQuotes: true,
        removeComments: true,
        removeEmptyAttributes: true,
        removeEmptyElements: false,
        removeOptionalTags: true,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true,
        removeTagWhitespace: false,
        sortAttributes: false,
        sortClassName: false,
        trimCustomFragments: false,
        useShortDoctype: true,
    };
    html = htmlMinifier.minify(html, minifiedOptions);
    log(
        chalk.bold('Size after minifier:'),
        chalk.blue(prettyBytes(html.length))
    );
    return html;
};
